### PR TITLE
Create check for script tags

### PR DESCRIPTION
**Pull request by nickbrowne**
This pulls the code from the existing rake task into a Check class that runs in the new rake task.

### CODE REVIEW

**Comment by nickbrowne** [comment]
[[i18n-hygiene] Create UnexpectedScriptTag Check class (check_script_tags rake task)](https://trello.com/c/uXkzP3wg/7773-i18n-hygiene-create-unexpectedscripttag-check-class-checkscripttags-rake-task)

**Comment by yob** [comment]
I've tested this in donations with the following config for the new rake task and confirmed it fails when there's a `<script>` tag in the `en` and `fr` locales:

```ruby
I18n::Hygiene::RakeTask.new(:hygiene) do |config|
  config.keys_to_skip = [
    "helpers.submit.create",
    "helpers.select.prompt", 
    "helpers.submit.submit",
    "helpers.submit.update",
   ]
  config.directories = ["app", "lib"]
  config.locales = [:fr]
  config.primary_locale = :en
end

```

**Comment by yob** [comment]
One thing I noticed is that it only picks up cases where the phrase has a opening *and* closing `<script>` tag - maybe it should detect either?

**Comment by nickbrowne** [comment]
> One thing I noticed is that it only picks up cases where the phrase has a opening and closing <script> tag - maybe it should detect either?

Yup, I've added a card for that.

**Pull request merged**
