### PR TITLE
Add some basic integration specs to make sure everything works

### PR DESCRIPTION
**Pull request by nickbrowne**
This sets up a few basic fixtures, with two rake tasks set to run against a valid translation and an invalid translation with a few assertions against each.

### CODE REVIEW

**Comment by nickbrowne** [comment]
~~I think there's something whacky going on with rvm and paths... one moment please.~~ Never mind we were just missing ag/ack in CI.

**Comment by nickbrowne** [comment]
These are pretty basic right now, I'd expect them to expand as we port more functionality over to the new system.

**Comment by keithpitty** [comment]
[[i18n-hygiene] Do we want some integration tests?](https://trello.com/c/ZmS0dtnK/7672-i18n-hygiene-do-we-want-some-integration-tests)

**Comment by keithpitty** [comment]
> These are pretty basic right now, I'd expect them to expand as we port more functionality over to the new system.

Excellent start! 👍

**Pull request merged**
